In [ ]:
#Variable and String
age = 10
print("I am",age,"years old")

I am 10 years old


In [ ]:
#Arithmetic operations on two integers
a=int(input("enter one number:"))
b=int(input("enter another number:"))
print("The sum is",a+b)
print("The difference is",a-b)
print("The product is",a*b)
print("The quotient is",a/b)
print("The remainder is",a%b)
print("The power is",a**b)
print("The floor quotient is",a//b)

enter one number:10
enter another number:2
The sum is 12
The difference is 8
The product is 20
The quotient is 5.0
The remainder is 0
The power is 100
The floor quotient is 5


In [ ]:
#Take a number from user which is his salary. If the salary is more than 50,000, there is a 10% tax(gets cut). Print his final salary.
#The default datatype of input is String.
sal = int(input("enter salary:"))
if( sal>=50000):
  tax = (10/100)*sal
  sal=sal-tax
  print("After tax deduction, your salary is:",sal)
else:
  print("No tax deduction. your salary is:",sal)

enter salary:60000
After tax deduction, your salary is: 54000.0


In [ ]:
#Get the salary from the user, if the salary is more than or equal to 50000, apply 10% tax deduction.
#if the salary is less than 50000, apply 5% tax. if the salary is more than 70000,apply 12% tax. If your salary exceeds 1lakh, print "you are promoted to next level"
sal=int(input("Enter Salary:"))
if sal>100000:
  print("You are Promoted")
elif sal>70000:
  tax=(12/100)*sal
  print("salary is",sal-tax)
elif sal>50000:
  tax=(10/100)*sal
  print("salary is",sal-tax)
else:
  tax=(5/100)*sal
  print("salary is",sal-tax)

Enter Salary:72000
salary is 63360.0


In [ ]:
#for loop
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
n= int(input("enter n:"))
for i in range(1,21):
  print(n,"X",i,"=",n*i)

enter n:15
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150
15 X 11 = 165
15 X 12 = 180
15 X 13 = 195
15 X 14 = 210
15 X 15 = 225
15 X 16 = 240
15 X 17 = 255
15 X 18 = 270
15 X 19 = 285
15 X 20 = 300


In [ ]:
n = int(input("Enter n:"))
i=1
while(i<=10):
  print(n,"X",i,"=",n*i)
  i=i+1

Enter n:18
18 X 1 = 18
18 X 2 = 36
18 X 3 = 54
18 X 4 = 72
18 X 5 = 90
18 X 6 = 108
18 X 7 = 126
18 X 8 = 144
18 X 9 = 162
18 X 10 = 180


In [ ]:
#Create a list
l=[17,"meow",True,36.6]
for i in l:
  print(i)

17
meow
True
36.6


In [ ]:
#Mutable
l.append("appended")# list_name.append(element)
print(l)

[17, 'meow', True, 36.6, 'appended']


In [ ]:
#insert at index : list_name.insert(index,element)
l.insert(4,"inserted")
print(l)

[17, 'meow', True, 36.6, 'inserted', 'appended']


In [ ]:
l2=["papaya","Berry"]
l.extend(l2) #l=l+l2
print(l)

[17, 'meow', True, 36.6, 'inserted', 'appended', 'papaya', 'Berry']


In [ ]:
l.pop(4)
print(l)
l.remove('meow')
print(l)

[17, 'meow', True, 'inserted']
[17, True, 'inserted']


In [ ]:
l=[19,'tom',89,False,"kitty"]
l.pop(3) #list_name.pop(index)
print(l)
l.remove('tom') #list_name.remove(element)
print(l)

[19, 'tom', 89, 'kitty']
[19, 89, 'kitty']


In [ ]:
l.clear() #list_name.clear()
print(l)

[]


In [ ]:
l=[24,56,13,24,57,10,42,33,6,9]
res=[]
for i in l:
  res.append(i*i)
print(res)

[576, 3136, 169, 576, 3249, 100, 1764, 1089, 36, 81]


In [ ]:
#Create a list of random 10 integers, print their squares. Save these squares in a new list
#list comprehension - list_name=[output for]
l=[24,56,13,24,57,10,42,33,6,9]
l3=[i*i for i in l]
print(l3)


[576, 3136, 169, 576, 3249, 100, 1764, 1089, 36, 81]


In [ ]:
l=[]
print("enter 10 numbers:")
for i in range(10):
  l.append(i)
ls=[i*i for i in l]
print(ls)

enter 10 numbers:
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
#list_name=[output for if]
l=[24,56,13,24,57,10,42,33,6,9]
res=[i*i for i in l if i>=50]
print(res)

[3136, 3249]


In [ ]:
#append if its greater than 50 ELSE X
#newlist=[(stat of if) if(cond) else (stat of else) for]
l=[24,56,13,24,57,10,42,33,6,9]
res=[i*i  if i>=50 else'X'for i in l]
print(res)

['X', 3136, 'X', 'X', 3249, 'X', 'X', 'X', 'X', 'X']


In [ ]:
#take the salary from the user. If salary is less than 50K,10% tax otherwise 15% tax.
#newlist=[(stat of if) if(cond) else (stat of else) for]
sal = int(input("enter salary:"))
taxr =["10% tax" if(sal<50000) else "15%tax"]
print(taxr)

enter salary:54000
['15%tax']


In [ ]:
li=[34000,10000,56000]
taxrr=[i-(10/100)*i if(i<50000) else i-(15/100)*i for i in li]
print(taxrr)

[30600.0, 9000.0, 47600.0]


In [ ]:
#Dictionary
#dictname={key:val,key:val,....}
#create a dictionary
dict1={'Mentor':'Jwalitha',12:'Ramya',15:'Pallavi',27:'Tanya',33:'Jyothsna',56:'Sahedha',98:'Praveena'}
print(dict1)

{'Mentor': 'Jwalitha', 12: 'Ramya', 15: 'Pallavi', 27: 'Tanya', 33: 'Jyothsna', 56: 'Sahedha', 98: 'Praveena'}


In [ ]:
#should be unique keys
dict1={'Mentor':'Jwalitha',12:'Ramya',15:'Pallavi',27:'Tanya',33:'Jyothsna',56:'Sahedha',33:'Praveena'}
print(dict1)

{'Mentor': 'Jwalitha', 12: 'Ramya', 15: 'Pallavi', 27: 'Tanya', 33: 'Praveena', 56: 'Sahedha'}


In [ ]:
#keys and values
print(dict1.keys())
print(dict1.values())
print(dict1[12])

dict_keys(['Mentor', 12, 15, 27, 33, 56])
dict_values(['Jwalitha', 'Ramya', 'Pallavi', 'Tanya', 'Praveena', 'Sahedha'])
Ramya


In [ ]:
dict3={'Dept':'CSE',"Details":{'YEAR':'II','Sec':'D','count':71}}
print(dict3)
print(dict3["Details"])
print(dict3["Details"]['Sec'])
print(dict3["Details"]['Sec'],dict3["Details"]['YEAR'],dict3["Details"]['count'])
print("Year is:",dict3["Details"]['YEAR'])
print("Strength is:",dict3["Details"]['count'])
print("Section is:",dict3["Details"]['Sec'])

{'Dept': 'CSE', 'Details': {'YEAR': 'II', 'Sec': 'D', 'count': 71}}
{'YEAR': 'II', 'Sec': 'D', 'count': 71}
D
D II 71
Year is: II
Strength is: 71
Section is: D


In [ ]:
#coupling two lists/tuples into a dictionary
id1=[12,45,67,78,89]
names=["Usha","Gayathri","Tanya","Jyo","Apparao"]
new_zip=(zip(id1,names))
for i in new_zip:
  print(i)

(12, 'Usha')
(45, 'Gayathri')
(67, 'Tanya')
(78, 'Jyo')
(89, 'Apparao')


In [ ]:
id1=[12,45,67,78,89]
names=["Usha","Gayathri","Tanya","Jyo","Apparao"]
print(dict(zip(id1,names)))

{12: 'Usha', 45: 'Gayathri', 67: 'Tanya', 78: 'Jyo', 89: 'Apparao'}


In [ ]:
#Numpy
import numpy as np
A=np.array([1,2,3,4]) #1D array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B) #elements in each row = columns
print(B.ndim)
print(B.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
C =np.array([[[1,2,3,4],[5,6,7,8]],[[9,8,7,6],[5,4,3,2]]])
print(C)
print(C.ndim)
print(C.shape) #(groupno,rowno in each group,colno in each group)
#no.of elements = i*j*k which are in shape.

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 8 7 6]
  [5 4 3 2]]]
3
(2, 2, 4)


In [ ]:
A=np.ones((2,3,4)) #g,r,c
print(A)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
A=np.zeros((2,3,4)) #g,r,c
print(A)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
A= np.eye(4) #Identity matrix
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A = np.arange(1,10,2)#Range of Numbers in an array (Start,stop,step)
print(A)
print(type(A))



[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#Print all the numbers that are divisible by 8 using arange function b/w 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#linspace is used to divide n parts of two numbers
#linspace - splitting a range into n numbers with common differences
A = np.linspace(38,45,13) #range is from 2 and 3 where 12 is the n parts division
print(A)

[38.         38.58333333 39.16666667 39.75       40.33333333 40.91666667
 41.5        42.08333333 42.66666667 43.25       43.83333333 44.41666667
 45.        ]


In [ ]:
#tuples,sets - study - seperate colab
#documentation
#QR code task

In [ ]:
a =[8,5,4,6,2]
a.sort()
print(a) #sort will sort the original list.

[2, 4, 5, 6, 8]


In [ ]:
l1=[34,56,21]
l1.sorted() #throws error since sorted() needs to be assigned to some other variable.
print(l1)

AttributeError: 'list' object has no attribute 'sorted'

In [ ]:
l2=sorted(l1)
print(l2)

[21, 34, 56]
