In [2]:
#ARRAY OPERATIONS
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B =np.linspace(12,24,20).reshape(5,4) #20 IS no of parts and these parts/elements can be arranged in 5x4
print(B)

[[12.         12.63157895 13.26315789 13.89473684]
 [14.52631579 15.15789474 15.78947368 16.42105263]
 [17.05263158 17.68421053 18.31578947 18.94736842]
 [19.57894737 20.21052632 20.84210526 21.47368421]
 [22.10526316 22.73684211 23.36842105 24.        ]]


In [ ]:
C=np.array([45,67,89,25,90,32,44,66,99]).reshape(3,3,1)# 9 elements into 3*3*1 (g,r,c)
print(C)

[[[45]
  [67]
  [89]]

 [[25]
  [90]
  [32]]

 [[44]
  [66]
  [99]]]


In [ ]:
D=np.array([45,67,89,25,90,32,44,66,99])
D.resize(3,3,1) #resize -changes the shape of original array
#reshape - changes needs saving in another variable
print(D)

[[[45]
  [67]
  [89]]

 [[25]
  [90]
  [32]]

 [[44]
  [66]
  [99]]]


In [ ]:
A =np.array([35,67,78,90]) #same no.of elements in both arrays. List can't support subtraction of each element from 2 lists
B=np.array([7,9,3,12])
C=A-B
print(C)


[28 58 75 78]


In [ ]:
A =np.array([35,67,78,90]) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12])
C=A+B
print(C)

[ 42  76  81 102]


In [3]:
A =np.array([35,67,78,90]) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12])
C=A+B
print(C)

[ 42  76  81 102]


In [ ]:
A =np.array([35,67,78,90]).reshape(2,2) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------------")
print(B)
print("------------------")
C=A*B #one-on-one multiplication
print(C)

[[35 67]
 [78 90]]
-------------------
[[ 7  9]
 [ 3 12]]
------------------
[[ 245  603]
 [ 234 1080]]


In [ ]:
A =np.array([35,67,78,90]).reshape(2,2) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------------")
print(B)
print("------------------")
C=A@B #matrix multiplication
print(C)

[[35 67]
 [78 90]]
-------------------
[[ 7  9]
 [ 3 12]]
------------------
[[ 446 1119]
 [ 816 1782]]


In [ ]:
A =np.array([35,67,78,90]).reshape(2,2) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------------")
print(B)
print("------------------")
C=A.dot(B) #matrix multiplication
print(C)

[[35 67]
 [78 90]]
-------------------
[[ 7  9]
 [ 3 12]]
------------------
[[ 446 1119]
 [ 816 1782]]


In [ ]:
A =np.array([35,67,78,90,90.1])
print(A.max())#max and min work for only numeric datatypes (int,float) and not for strings
print(A.min())

90.1
35.0


In [ ]:
A =np.array([35,67,78,90,88,44,33,23]).reshape(2,4)

print(A)
print("-------------------")
print(A.max(axis=0))#columnwise bigger numbers
print("-------------------")
print(A.max(axis=1))#row-wise bigger numbers
print("-------------------")
print(A.min(axis=0))#col min
print("-------------------")
print(A.min(axis=1))#row min

[[35 67 78 90]
 [88 44 33 23]]
-------------------
[88 67 78 90]
-------------------
[90 88]
-------------------
[35 44 33 23]
-------------------
[35 23]


In [ ]:
#Joining arrays - stack
#vertical joining - vstack
#horizontal joining -hstack
A =np.array([35,67,78,90]).reshape(2,2) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------------")
print(B)
print("------------------")
print("After vertically stacking the arrays_")
print(np.vstack((A,B)))# vstack only takes one parameter. so double inside the paranthesis,both the arrays r sent.

[[35 67]
 [78 90]]
-------------------
[[ 7  9]
 [ 3 12]]
------------------
After vertically stacking the arrays_
[[35 67]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
A =np.array([35,67,78,90]).reshape(2,2) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------------")
print(B)
print("------------------")
print("After vertically stacking the arrays_")
print(np.stack((A,B),axis=0))# v stack since axis=0(col) ,3D. If axis=1, Hstack.

[[35 67]
 [78 90]]
-------------------
[[ 7  9]
 [ 3 12]]
------------------
After vertically stacking the arrays_
[[[35 67]
  [78 90]]

 [[ 7  9]
  [ 3 12]]]


In [ ]:
A =np.array([35,67,78,90]).reshape(2,2) #same no.of elements in both arrays. List Does Concatenation of lists
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------------")
print(B)
print("------------------")
print("After horizontally stacking the arrays_")
print(np.stack((A,B),axis=1))#not working as hstack

[[35 67]
 [78 90]]
-------------------
[[ 7  9]
 [ 3 12]]
------------------
After horizontally stacking the arrays_
[[[35 67]
  [ 7  9]]

 [[78 90]
  [ 3 12]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))#stack acc to dimensions
#no.of rows--->no.of groups
#no.of col in every group ---> no.of rows in every group
#[0,0],[1,1]....colwise stack but place in rows.

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
A=np.arange(18).reshape(6,3)#Based on rows, vsplit is possible. rows=6, so you can divide by 2 or 3 or 6 parts.
print(A)
print("After splitting")
print(np.vsplit(A,3))# vsplit means splitting from top to bottom equally
print("---------------------")
print(np.vsplit(A,(2,5))) #split at top of index 2 and top of index5. Index count from 0.
print("---------------------")
print(np.hsplit(A,3))#splitting from left to right by hand
print("---------------------")
print(np.vsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]
---------------------
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]
---------------------
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]
---------------------
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)#Based on cols, hsplit is possible. cols=6, so you can divide by 2 or 3 or 6 parts.
print(A)
print("After splitting")
print(np.hsplit(A,3)) # hsplit means splitting from left to right equally
print("----------------------------------")
print(np.hsplit(A,(1,2)))#split at left of index 2 and left of index5. Index count from 0.

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]
----------------------------------
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
A= np.array([54,67,99,21,13,66]).reshape(2,3)
print(A)
print(A.argmax()) #returns the index of max number.
print(A.argmax(axis=0))# given the parameter as axis=0,  returs the index of max number columnwise.
#axis=0
#0 0 0 0
#1 1 1 1
#2 2 2 2
print("---------------------")
print(A.argmax(axis=1))# given the parameter as axis=1,  returs the index of max number row-wise.
#axis=1
#0 1 2 3
#0 1 2 3
#0 1 2 3
print("---------------------")
print(A.argmin(axis=0))#given the parameter as axis=0,  returs the index of minnumber columnwise.


print("---------------------")
print(A.argmin(axis=1))#given the parameter as axis=1,  returs the index of min number rowwise.


[[54 67 99]
 [21 13 66]]
2
[0 0 0]
---------------------
[2 2]
---------------------
[1 1 1]
---------------------
[0 1]


In [ ]:
#Numpy Statistics: formulae should be in doc
A= np.array([54,67,99,21,13,66])
print("Mean:",np.mean(A))
print("MeDIAN:",np.median(A))
print("Variance:",np.var(A))
print("Standard deviation:",np.std(A))

Mean: 53.333333333333336
MeDIAN: 60.0
Variance: 850.888888888889
Standard deviation: 29.169999809545576


In [ ]:
A=np.pi
print(A)#RADIANS
np.rad2deg(A)#radians into degree

3.141592653589793


180.0

In [ ]:
A =[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
print(np.rad2deg(A))


[3093.97209371 3838.81722738 5672.2821718  1203.21136977  744.84513367
 3781.52144786]


In [ ]:
C= np.array([0,30,45,60,90,120,180])
D=(np.deg2rad(C)) #deg to radians
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.cos(C)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362,  0.81418097,
       -0.59846007])

In [ ]:
#sin^-1
np.arcsin(1)

1.5707963267948966

In [ ]:
#cos^-1
np.arccos(1)

0.0

In [ ]:
#tan^-1
np.arctan(1)

0.7853981633974483

In [ ]:
#no funcs for cosec,sec,cot.
#hypotenus
a=12
b=42
print(np.hypot(a,b))

43.68065933568311


In [ ]:
#SEARCHING based on relational conditions returns index/s anytime.
A=np.array([90,3,90,45,66])
print(np.where(A==90))

(array([0, 2]),)


In [ ]:
print(np.where(A%2==0)) #Even
print(np.where(A>25))

(array([0, 2, 4]),)
(array([0, 2, 3, 4]),)


In [ ]:
import numpy as np
A=np.array([23,59,70,45,56,75,89])
print(A)
print(np.searchsorted(A,56))


[23 59 70 45 56 75 89]
4


In [ ]:
A=np.array([23,59,70,45,56,75,89])
B=np.array([56,43,12,89,89,57,10])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.mod(A,B))
print(np.divide(A,B))
print(np.sort(A))
print(np.divmod(A,B))
print(np.diff(A))#current-past


[ 79 102  82 134 145 132  99]
[-33  16  58 -44 -33  18  79]
[23 16 10 45 56 18  9]
[0.41071429 1.37209302 5.83333333 0.50561798 0.62921348 1.31578947
 8.9       ]
[23 45 56 59 70 75 89]
(array([0, 1, 5, 0, 0, 1, 8]), array([23, 16, 10, 45, 56, 18,  9]))
[ 36  11 -25  11  19  14]


In [ ]:
#set operations on array
A=np.array([23,59,70,45,56,75,89])
B=np.array([56,43,12,89,89,57,10])
print(np.intersect1d(A,B))
print(np.setdiff1d(A,B))

[56 89]
[23 45 59 70 75]


**Rounding Functions:**

In [ ]:
a=np.fix([-3.1666,3.667])#truncating
print(a)

[-3.  3.]


In [ ]:
a=np.trunc([-3.1666,3.667])#truncating
print(a)

[-3.  3.]


In [ ]:
a=np.around([-3.1666,3.667])#rounding
print(a)

[-3.  4.]


In [ ]:
a=np.floor([-3.1666,3.667])#flooring
print(a)

[-4.  3.]


In [ ]:
a=np.ceil([-3.1666,3.667])#ceiling
print(a)

[-3.  4.]


In [ ]:
B=np.array([56,43,12,89,89,57,10])
print(np.cumsum(B))

[ 56  99 111 200 289 346 356]


In [ ]:
B=np.array([56,43,12,89,89,57,10])
print(np.cumprod(B))

[          56         2408        28896      2571744    228885216
  13046457312 130464573120]


In [ ]:
C=np.array([0,1,1])
print(np.cumsum(C))

[ 0  1  3  6 10 15 21 28 36 45]


In [ ]:
print(np.lcm(24,6)) #lcm good upto 2 parameters. for 3 parameters,reduce() comes into picture
print(np.gcd(12,84))

24
12


In [ ]:
#Using reduce()function to take n parameters for working.
Ar=np.array([45,90,180])
print(np.lcm.reduce(Ar))
print(np.gcd.reduce(Ar))

180
45


In [ ]:
#Adjacency matrix
#A^-1 = 1/(ad-bc)[d  -b]
#                [-c   a]
#Random module
from numpy import random as rd
A=rd.rand() #generates 0 to 0.99 by default
print(A)

0.19189620688503106


In [ ]:
A=rd.rand(10)#generates 10 numbers from 0 to 0.99
print(A)

[0.53933728 0.70073056 0.20840973 0.39416982 0.87366355 0.54544827
 0.70459995 0.46272478 0.74819211 0.83339884]


In [ ]:
A=rd.randint(10)#generates any number in from 0 to 10
print(A)

8


In [ ]:
A=rd.randint(10,size=3)#generates 3 number/s in from 0 to 10
print(A)

[5 4 5]


In [ ]:
A=rd.randint(30,size=(3,2))#generates 3x2 matrix  from 0 to 30
print(A)

[[ 9 20]
 [25 27]
 [11  8]]


In [ ]:
A=np.array([1,2,3])#Inner join
B=np.array([4,5,6])
#1x4+2x5+3x6
print(np.inner(A,B))

32


In [ ]:
A=np.array([1,2,3])#Outer join
B=np.array([4,5,6])

print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])#Cross join -works kinda like det
B=np.array([4,5,6])
#2*6-5*3 , -(1*6-4*3) , 1*5-2*4
print(np.cross(A,B))

[-3  6 -3]
